language: objective-c
osx_image: xcode9
env:
  global:
  - IOS_FRAMEWORK_SCHEME="NotchyAlert"
  - IOS_PROJECT="Notchy.xcodeproj"
  - IOS_SDK=iphonesimulator11.0
  matrix:
   - DESTINATION="name=iPhone X" BUILD_EXAMPLE="NO" POD_LINT="NO"
cache:
  directories:
  - Carthage
before_install:
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.18.1/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - curl -L -O https://github.com/YPlan/CartfileDiff/releases/download/0.1/CartfileDiff.pkg
  - sudo installer -pkg CartfileDiff.pkg -target /
  - gem install xcpretty
install: true
script:
  - xcrun instruments -w "*"
  - xcodebuild -project "Notchy.xcodeproj" -scheme "NotchyAlert" -sdk "iphonesimulator11.0" -destination "name=iPhone 6s" -configuration Debug ONLY_ACTIVE_ARCH=NO build
notifications:
  email:
    recipients:
      - theabstractdev@gmail.com
    on_success: change
    on_failure: always
