language: objective-c
osx_image: xcode9
env:
  global:
  - IOS_FRAMEWORK_SCHEME="NotchyAlert"
  - IOS_PROJECT="Notchy.xcodeproj"
  - IOS_SDK=iphonesimulator11.0
  matrix:
   - DESTINATION="OS=11.0,name=iPhone X" SDK="$IOS_SDK" SCHEME="$IOS_FRAMEWORK_SCHEME" BUILD_EXAMPLE="NO" POD_LINT="NO"
script:
  - set -o pipefail
  # Build Framework in ReleaseTest
  - xcodebuild -project "$IOS_PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c