language: objective-c
osx_image: xcode9
env:
  global:
  - FRAMEWORK_SCHEME="NotchyAlert"
  - PROJECT="NotchyAlert.xcodeproj"
  - SDK=iphonesimulator11.0
  - DESTINATION="platform=iOS Simulator,OS=11.0,name=iPhone2017-C" BUILD_EXAMPLE="NO"
before_install:
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.18.1/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - gem install xcpretty
install: true
script:
  - set -o pipefail
  - xcodebuild -project "$PROJECT" -scheme "$FRAMEWORK_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty
notifications:
  email:
    recipients:
      - theabstractdev@gmail.com
    on_success: change
    on_failure: always